channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2 =2.5.3
  - csvkit =1.4.0
  - fastp =0.23.4
  - gzip =1.13
  - kraken2 =2.1.3
  - nonpareil =3.4.1
  - parallel =20240122
  - pigz =2.8
  - r-argparse =2.2.2
  - r-nonpareil =3.4.0
  - r-tidyverse =2.0.0
  - rsync =3.2.7
  - samtools =1.19.2
  - singlem =0.16.0
  - smafa =0.7.0  # singlem 0.16.0 fails with smafa 0.8
